ALTER TABLE public.food_entries
  ADD COLUMN IF NOT EXISTS meal TEXT NOT NULL DEFAULT 'breakfast',
  ADD COLUMN IF NOT EXISTS carbs NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fat NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS quantity NUMERIC NOT NULL DEFAULT 1;